# Lesson 8 Exercise 3 - Lecturer Version

In [7]:
# prompt: read text from text file as a single string, removing new line characters
def read_text_file(file_path):
    with open(file_path, 'r') as file:
        file_contents = file.read().replace('\n', '')
    return file_contents

# Example usage
file_path = 'ex_8_3_corpus.txt'  # Replace with the path to your file
text = read_text_file(file_path)

print(text)

Cambodia,[a] officially the Kingdom of Cambodia,[b] is a country in Southeast Asia on the Indochinese Peninsula. It is bordered by Thailand to the northwest, Laos to the north, and Vietnam to the east, and has a coastline along the Gulf of Thailand in the southwest. It spans an area of 181,035 square kilometres (69,898 square miles), dominated by a low-lying plain and the confluence of the Mekong river and Tonlé Sap, Southeast Asia's largest lake. It is dominated by a tropical climate and is rich in wildlife and biodiversity. Cambodia has a population of about 17 million people,[15] the majority of which are ethnically Khmer. Its capital and most populous city is Phnom Penh, followed by Siem Reap and Battambang.In 802 AD, Jayavarman II declared himself king, uniting the warring Khmer princes of Chenla under the name "Kambuja".[16] This marked the beginning of the Khmer Empire. The Indianised kingdom facilitated the spread of first Hinduism and then Buddhism to Southeast Asia and undert

In [8]:
import re

text = re.sub(r'[^\w\s]', '', text)
print(text)

Cambodiaa officially the Kingdom of Cambodiab is a country in Southeast Asia on the Indochinese Peninsula It is bordered by Thailand to the northwest Laos to the north and Vietnam to the east and has a coastline along the Gulf of Thailand in the southwest It spans an area of 181035 square kilometres 69898 square miles dominated by a lowlying plain and the confluence of the Mekong river and Tonlé Sap Southeast Asias largest lake It is dominated by a tropical climate and is rich in wildlife and biodiversity Cambodia has a population of about 17 million people15 the majority of which are ethnically Khmer Its capital and most populous city is Phnom Penh followed by Siem Reap and BattambangIn 802 AD Jayavarman II declared himself king uniting the warring Khmer princes of Chenla under the name Kambuja16 This marked the beginning of the Khmer Empire The Indianised kingdom facilitated the spread of first Hinduism and then Buddhism to Southeast Asia and undertook religious infrastructural proje

In [9]:
import nltk
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt_tab to
[nltk_data]     /Users/maohieng/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!


True

In [10]:
from nltk.tokenize import word_tokenize

tokens = word_tokenize(text)
print(tokens)

['Cambodiaa', 'officially', 'the', 'Kingdom', 'of', 'Cambodiab', 'is', 'a', 'country', 'in', 'Southeast', 'Asia', 'on', 'the', 'Indochinese', 'Peninsula', 'It', 'is', 'bordered', 'by', 'Thailand', 'to', 'the', 'northwest', 'Laos', 'to', 'the', 'north', 'and', 'Vietnam', 'to', 'the', 'east', 'and', 'has', 'a', 'coastline', 'along', 'the', 'Gulf', 'of', 'Thailand', 'in', 'the', 'southwest', 'It', 'spans', 'an', 'area', 'of', '181035', 'square', 'kilometres', '69898', 'square', 'miles', 'dominated', 'by', 'a', 'lowlying', 'plain', 'and', 'the', 'confluence', 'of', 'the', 'Mekong', 'river', 'and', 'Tonlé', 'Sap', 'Southeast', 'Asias', 'largest', 'lake', 'It', 'is', 'dominated', 'by', 'a', 'tropical', 'climate', 'and', 'is', 'rich', 'in', 'wildlife', 'and', 'biodiversity', 'Cambodia', 'has', 'a', 'population', 'of', 'about', '17', 'million', 'people15', 'the', 'majority', 'of', 'which', 'are', 'ethnically', 'Khmer', 'Its', 'capital', 'and', 'most', 'populous', 'city', 'is', 'Phnom', 'Penh',

In [11]:
from collections import Counter

vocab = Counter(tokens).most_common(50)
print(vocab)

[('the', 173), ('of', 95), ('and', 83), ('in', 70), ('to', 47), ('a', 39), ('was', 26), ('Cambodia', 24), ('The', 24), ('is', 23), ('Khmer', 23), ('from', 21), ('by', 20), ('as', 19), ('were', 16), ('which', 13), ('Sihanouk', 13), ('Vietnamese', 12), ('that', 11), ('Cambodian', 10), ('with', 10), ('on', 9), ('Vietnam', 8), ('Rouge', 8), ('his', 8), ('an', 7), ('Angkor', 7), ('during', 7), ('its', 7), ('their', 7), ('country', 6), ('Southeast', 6), ('most', 6), ('In', 6), ('until', 6), ('other', 6), ('US', 6), ('Thailand', 5), ('population', 5), ('about', 5), ('are', 5), ('name', 5), ('began', 5), ('became', 5), ('War', 5), ('France', 5), ('1970', 5), ('official', 5), ('Kâmpŭchéa', 5), ('while', 5)]


In [12]:
word_to_index = {}
for i, (word, count) in enumerate(vocab):
    word_to_index[word] = i

tokens_index = []
for token in tokens:
  if token in word_to_index:
    tokens_index.append(word_to_index[token])
  else:
    tokens_index.append(-1)

print(tokens_index)

[-1, -1, 0, -1, 1, -1, 9, 5, 30, 3, 31, -1, 21, 0, -1, -1, -1, 9, -1, 12, 37, 4, 0, -1, -1, 4, 0, -1, 2, 22, 4, 0, -1, 2, -1, 5, -1, -1, 0, -1, 1, 37, 3, 0, -1, -1, -1, 25, -1, 1, -1, -1, -1, -1, -1, -1, -1, 12, 5, -1, -1, 2, 0, -1, 1, 0, -1, -1, 2, -1, -1, 31, -1, -1, -1, -1, 9, -1, 12, 5, -1, -1, 2, 9, -1, 3, -1, 2, -1, 7, -1, 5, 38, 1, 39, -1, -1, -1, 0, -1, 1, 15, 40, -1, 10, -1, -1, 2, 32, -1, -1, 9, -1, -1, -1, 12, -1, -1, 2, -1, -1, -1, -1, -1, -1, -1, -1, -1, 0, -1, 10, -1, 1, -1, -1, 0, 41, -1, -1, -1, 0, -1, 1, 0, 10, -1, 8, -1, -1, -1, 0, -1, 1, -1, -1, 2, -1, -1, 4, 31, -1, 2, -1, -1, -1, -1, -1, 0, -1, 0, 32, -1, 1, 15, 9, 26, -1, 33, 0, -1, -1, -1, 42, 5, -1, 3, -1, 34, 3, -1, 7, 43, 5, -1, -1, -1, -1, -1, 27, -1, 44, -1, 7, -1, -1, 11, 45, 3, -1, 8, 22, 44, -1, 0, 30, 3, -1, -1, 27, 0, -1, -1, 3, 5, 46, -1, 15, -1, 0, -1, 10, -1, 2, 0, -1, 1, 0, -1, 10, 23, 3, -1, 8, 10, 23, -1, 0, 30, 2, -1, -1, 0, 19, -1, 11, -1, 34, -1, 34, -1, 14, -1, 27, 0, -1, 44, -1, 6, -1, 12, 0,

In [13]:
# term-term co-occurrence matrix
import numpy as np

window_size = 4
num_words = len(vocab)
co_occurrence_matrix = np.zeros((num_words, num_words))

for i in range(len(tokens_index)):
    if tokens_index[i] == -1:
        continue
    for j in range(i - window_size, i + window_size + 1):
        if j < 0 or j >= len(tokens_index) or i == j or tokens_index[j] == -1:
            continue
        co_occurrence_matrix[tokens_index[i]][tokens_index[j]] += 1

print(co_occurrence_matrix)


[[68. 81. 46. ...  4.  3.  3.]
 [81. 16. 25. ...  3.  1.  1.]
 [46. 25. 10. ...  1.  0.  1.]
 ...
 [ 4.  3.  1. ...  0.  0.  0.]
 [ 3.  1.  0. ...  0.  2.  0.]
 [ 3.  1.  1. ...  0.  0.  0.]]
