In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd  # Assuming time_series is a pandas DataFrame or Series

In [2]:
# Define the time series and window length
time_series = np.array([1, 1.1, 0, 0.6, -1])
L = 2

In [4]:
# Construct the trajectory matrix
K = len(time_series) - L + 1
trajectory_matrix = np.zeros((K, L))
for i in range(K):
    trajectory_matrix[i] = time_series[i:i + L]

# Perform SVD
U, Sigma, Vt = np.linalg.svd(trajectory_matrix)

U, Sigma, Vt

(array([[-0.84749103,  0.04914732, -0.3490736 ,  0.39685151],
        [-0.44392387, -0.54062051,  0.23405267, -0.67518917],
        [-0.24214029,  0.29488391,  0.8944562 ,  0.2331516 ],
        [ 0.16142686, -0.7863571 ,  0.15269276,  0.57642762]]),
 array([1.75214155, 1.43874946]),
 array([[-0.70710678, -0.70710678],
        [-0.70710678,  0.70710678]]))

In [5]:

# Reconstruct the elementary matrices
elementary_matrices = np.array([Sigma[i] * np.outer(U[:, i], Vt[i, :]) for i in range(L)])

elementary_matrices

array([[[ 1.05,  1.05],
        [ 0.55,  0.55],
        [ 0.3 ,  0.3 ],
        [-0.2 , -0.2 ]],

       [[-0.05,  0.05],
        [ 0.55, -0.55],
        [-0.3 ,  0.3 ],
        [ 0.8 , -0.8 ]]])

In [6]:
# Sum the elementary matrices to get the approximated trajectory matrix
approx_trajectory_matrix = np.sum(elementary_matrices, axis=0)

approx_trajectory_matrix

array([[ 1. ,  1.1],
       [ 1.1,  0. ],
       [ 0. ,  0.6],
       [ 0.6, -1. ]])

In [10]:
# Average the anti-diagonals to get the reconstructed time series
reconstructed_series = np.zeros(len(time_series))
count = np.zeros(len(time_series))

for i in range(K):
    for j in range(L):
        reconstructed_series[i + j] += approx_trajectory_matrix[i, j]
        count[i + j] += 1

reconstructed_series /= count

reconstructed_series

array([ 1. ,  1.1,  0. ,  0.6, -1. ])