In [157]:
import numpy as np
import tensorflow as tf
from khmernltk import word_tokenize

N = 5
H = 512

In [158]:
embedding = np.load("data/word_embeddings.npy")
embedding.shape, embedding

((172, 50),
 array([[ 0.07586228, -0.15236232, -0.09072954, ..., -0.0034957 ,
         -0.4506731 ,  0.30250466],
        [-0.34170637, -0.01606815,  0.31439087, ...,  0.42224994,
          0.07888315,  0.01614269],
        [-0.14733146, -0.10289677,  0.11139668, ...,  0.19297075,
         -0.01175855,  0.01021618],
        ...,
        [ 0.38235813,  0.35910478,  0.08166692, ..., -0.25959334,
         -0.09625811, -0.24121079],
        [ 0.2116009 ,  0.06986097, -0.05244661, ..., -0.07107236,
         -0.31267273,  0.00909469],
        [-0.12669647,  0.25969973,  0.13957992, ...,  0.5100123 ,
          0.07320362,  0.05986629]], dtype=float32))

In [159]:
word_to_embeddings = np.load("data/word_to_embeddings.npy", allow_pickle=True).item()
word_to_embeddings

{'ចូល': array([ 0.07586228, -0.15236232, -0.09072954, -0.32267177,  0.04369213,
        -0.09427623, -0.04054638,  0.2460587 ,  0.30426112,  0.1302389 ,
        -0.07594767, -0.10918866, -0.05294536, -0.04367377,  0.0680489 ,
        -0.15298752, -0.14382862,  0.08102842,  0.08398345,  0.03126803,
         0.0174115 , -0.06121962,  0.19692384, -0.01143637, -0.11729819,
         0.01543533,  0.2810284 , -0.13549674, -0.16842571,  0.23949823,
        -0.19157858,  0.06749626, -0.09666322,  0.17225336, -0.07730738,
        -0.17376481,  0.25533125, -0.31552076, -0.4435677 , -0.21189679,
        -0.12988505, -0.12456946, -0.23487428,  0.05655387,  0.03963018,
         0.1552369 , -0.13885418, -0.0034957 , -0.4506731 ,  0.30250466],
       dtype=float32),
 'ស្ថាបត្យកម្ម': array([-0.34170637, -0.01606815,  0.31439087,  0.48047888,  0.22913742,
         0.41612294,  0.4373974 , -0.19126223,  0.1087551 , -0.1795352 ,
        -0.14642192,  0.10140985,  0.01401141,  0.17410633,  0.2231851 ,
    

In [160]:
with open("data/temples_cleaned.txt") as f:
    text = f.read()
text

'ប្រាសាទអង្គរវត្តឬប្រាសាទអង្គរតូចមានទីតាំងស្ថិតនៅភាគខាងជើងនៃក្រុងសៀមរាបនៃខេត្តសៀមរាបប្រាសាទអង្គរវត្តជាប្រាសាទព្រហ្មញ្ញសាសនាធំបំផុតនិងជាវិមានសាសនាដ៏ធំបំផុតនៅក្នុងលោកប្រាសាទនេះត្រូវបានកសាងឡើងដោយព្រះបាទសូរ្យវរ្ម័នទី២ដែលជាស្នាដៃដ៏ធំអស្ចារ្យនិងមានឈ្មោះល្បីល្បាញរន្ទឺសុះសាយទៅគ្រប់ទិសទីលើពិភពលោកប្រាសាទនេះសាងសង់ឡើងនៅដើមសតវត្សទី១២ដែលស្ថិតនៅក្នុងរាជធានីយសោធរបុរៈប្រាសាទអង្គរវត្តជាប្រាសាទកសាងឡើងដើម្បីឧទ្ទិសដល់ព្រះវិស្ណុប្រាសាទនេះជាប្រាសាទដែលនៅគង់វង្សល្អបំផុតនៅក្នុងតំបន់អង្គរប្រាសាទអង្គរវត្តប្រើកម្លាំងពលកម្មប្រម៉ាណជាងមុឺននាក់និងដំរីជាងពាន់ក្បាលនិងប្រើប្រាស់ថ្មសរុបប្រមាណជាងលានតោននៅក្នុងប្រាសាទមានចម្លាក់អប្សរាយ៉ាងស្អាតចំណែកឯទីធ្លាខាងក្រៅមានដើមត្នោតរួមទាំងទេសភាពដ៏ស្រស់បំព្រងហើយនៅជុំវិញប្រាសាទប្រាសាទអង្គរវត្តត្រូវបានរចនាដើម្បីតំណាងភ្នំព្រះសុមេរុដែលជាទីលំនៅរបស់អាទិទេពនិងទេវតាក្នុងទេវកថាហិណ្ឌូដែលមានកសិ្សណឬគូទឹកព័ទ្ធជុំវិញប្រហែលជា១៦គីឡូម៉ែត្រចំណែកកសិ្សណពិតប្រាកដរបស់ប្រាសាទមានបណ្តោយប្រវែង១៥០០ម៉ែត្រទទឹង១៣០០ម៉ែត្រលើ២០០ម៉ែត្រផ្លូវធំដើរចូលពីទិសខាងលិចទៅដល់ប្រាសាទកណ្តាលមានប្រវែង២៥០ម៉ែត្រឯកំពូលកណ្ដាលខ្ពស់ធំជាងគេបំ

In [161]:
with open("data/vocab.txt") as f:
    vocab = f.read().splitlines()
len(vocab), vocab

(172,
 ['ចូល',
  'ស្ថាបត្យកម្ម',
  'មួយ',
  'ពី',
  'ភ្នំ',
  'ខាងលិច',
  'ខ្មែរ',
  'ចុង',
  'ពួក',
  'ជាមួយ',
  'ច្រក',
  'អ្នក',
  'ប្រហែល',
  'ទេវតា',
  'ធំ',
  'ក្នុង',
  'គ្នា',
  'ម៉ែត្រ',
  'នឹង',
  'លើ',
  'ហើយ',
  'ខ្ពស់',
  'ចំពោះ',
  'ព័ទ្ធ',
  'ដូចជា',
  'ទាំងអស់',
  'ធ្វើ',
  'ដើម',
  'ឆ្នាំ',
  'នៃ',
  'ប្រមាណ',
  'ក្បាច់',
  'ផ្សេង',
  'របស់',
  'មិន',
  'ឈ្មោះ',
  'ចេញ',
  'ស្រុក',
  'បុរាណ',
  'ដំបូង',
  'អាច',
  'អង្គរ',
  'តំណាង',
  'ខេត្ត',
  'ប្រវែង',
  'កំពែង',
  'នោះ',
  'ប្រទេស',
  'តែ',
  'សាសនា',
  'នូវ',
  'ប្រាសាទ',
  'ដោយ',
  'បី',
  'ទៅ',
  'ខាងក្រៅ',
  'ថ្ម',
  'ខាងជើង',
  'នៅក្នុង',
  'មក',
  'សំណង់',
  'សតវត្សរ៍',
  'ទី',
  'បុរៈ',
  'ស្ថិត',
  'ថ្ងៃ',
  'ទឹក',
  'ប៉ម',
  'ពាក្យ',
  'ដើម្បី',
  'ដ៏',
  'ឃើញ',
  'គឺជា',
  'នៅ',
  'ដី',
  'ថា',
  'អោយ',
  'តាម',
  'ចំនួន',
  'ផ្លូវ',
  'គេ',
  'ន័យ',
  'កំពុង',
  'រចនាបថ',
  'វិញ',
  'ផងដែរ',
  'ប្រើ',
  'ជាប់',
  'ដំបូល',
  'នគរ',
  'ជុំវិញ',
  'កន្លែង',
  'ទេសចរណ៍',
  'រាង',
  'មាន',
  'និង',
  'ហៅ',
 

In [162]:
tokens = word_tokenize(text)
tokens

['ប្រាសាទ',
 'អង្គរវត្ត',
 'ឬ',
 'ប្រាសាទ',
 'អង្គរ',
 'តូច',
 'មាន',
 'ទីតាំង',
 'ស្ថិត',
 'នៅ',
 'ភាគ',
 'ខាងជើង',
 'នៃ',
 'ក្រុង',
 'សៀមរាប',
 'នៃ',
 'ខេត្ត',
 'សៀមរាប',
 'ប្រាសាទ',
 'អង្គរវត្ត',
 'ជា',
 'ប្រាសាទ',
 'ព្រហ្មញ្ញ',
 'សាសនា',
 'ធំ',
 'បំផុត',
 'និង',
 'ជា',
 'វិមាន',
 'សាសនា',
 'ដ៏',
 'ធំ',
 'បំផុត',
 'នៅក្នុង',
 'លោក',
 'ប្រាសាទ',
 'នេះ',
 'ត្រូវបាន',
 'កសាងឡើង',
 'ដោយ',
 'ព្រះបាទ',
 'សូរ្យ',
 'វរ្ម័ន',
 'ទី២',
 'ដែល',
 'ជា',
 'ស្នាដៃ',
 'ដ៏',
 'ធំ',
 'អស្ចារ្យ',
 'និង',
 'មាន',
 'ឈ្មោះ',
 'ល្បីល្បាញ',
 'រន្ទឺ',
 'សុះ',
 'សាយ',
 'ទៅ',
 'គ្រប់',
 'ទិសទី',
 'លើ',
 'ពិភពលោក',
 'ប្រាសាទ',
 'នេះ',
 'សាងសង់',
 'ឡើង',
 'នៅ',
 'ដើម',
 'សតវត្ស',
 'ទី',
 '១២',
 'ដែល',
 'ស្ថិត',
 'នៅក្នុង',
 'រាជធានីយ',
 'សោធរ',
 'បុរៈ',
 'ប្រាសាទ',
 'អង្គរវត្ត',
 'ជា',
 'ប្រាសាទ',
 'កសាងឡើង',
 'ដើម្បី',
 'ឧទ្ទិស',
 'ដល់',
 'ព្រះវិស្ណុ',
 'ប្រាសាទ',
 'នេះ',
 'ជា',
 'ប្រាសាទ',
 'ដែល',
 'នៅ',
 'គង់វង្ស',
 'ល្អ',
 'បំផុត',
 'នៅក្នុង',
 'តំបន់',
 'អង្គរ',
 'ប្រាសាទ',
 'អង្គរវត្ត',
 'ប្រើ',
 'កម្លាំង'

In [163]:
model = tf.keras.Sequential()
model.add(tf.keras.layers.Embedding(input_dim=embedding.shape[0], output_dim=embedding.shape[1], weights=[embedding], input_length=N, trainable=False))
model.add(tf.keras.layers.Flatten())
model.add(tf.keras.layers.Dense(H, activation='sigmoid'))
model.add(tf.keras.layers.Dense(len(vocab), activation='softmax'))

model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])
model.summary()

Model: "sequential_27"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_26 (Embedding)    (None, 5, 50)             8600      
                                                                 
 flatten_5 (Flatten)         (None, 250)               0         
                                                                 
 dense_28 (Dense)            (None, 512)               128512    
                                                                 
 dense_29 (Dense)            (None, 172)               88236     
                                                                 
Total params: 225348 (880.27 KB)
Trainable params: 216748 (846.67 KB)
Non-trainable params: 8600 (33.59 KB)
_________________________________________________________________


In [164]:
# Create training data
X = []
y = []
for i in range(len(tokens) - N):
    X.append(tokens[i:i+N])
    y.append(tokens[i+N])

X = np.array(X)
y = np.array(y)
X.shape, y.shape

((9165, 5), (9165,))

In [165]:
X, y

(array([['ប្រាសាទ', 'អង្គរវត្ត', 'ឬ', 'ប្រាសាទ', 'អង្គរ'],
        ['អង្គរវត្ត', 'ឬ', 'ប្រាសាទ', 'អង្គរ', 'តូច'],
        ['ឬ', 'ប្រាសាទ', 'អង្គរ', 'តូច', 'មាន'],
        ...,
        ['នៅតែ', 'បន្ត', 'រហូតមក', 'ទល់', 'សព្វ'],
        ['បន្ត', 'រហូតមក', 'ទល់', 'សព្វ', 'ថៃ្ង'],
        ['រហូតមក', 'ទល់', 'សព្វ', 'ថៃ្ង', 'នេះ']], dtype='<U20'),
 array(['តូច', 'មាន', 'ទីតាំង', ..., 'ថៃ្ង', 'នេះ', '៤'], dtype='<U20'))

In [166]:
# Convert words to indices
X = np.array([[vocab.index(w) if w in vocab else 0 for w in x] for x in X])
y = np.array([vocab.index(w) if w in vocab else 0 for w in y])
X, y

(array([[ 51, 125, 161,  51,  41],
        [125, 161,  51,  41, 159],
        [161,  51,  41, 159,  94],
        ...,
        [  0,   0,   0,   0,   0],
        [  0,   0,   0,   0,   0],
        [  0,   0,   0,   0, 122]]),
 array([159,  94,   0, ...,   0, 122,   0]))

In [167]:
# Remove rows with unknown words
mask = np.all(X != 0, axis=1)
X = X[mask]
y = y[mask]
X.shape, y.shape, X[:5], y[:5]

((633, 5),
 (633,),
 array([[ 51, 125, 161,  51,  41],
        [125, 161,  51,  41, 159],
        [161,  51,  41, 159,  94],
        [ 64,  73, 140,  57,  29],
        [ 73, 140,  57,  29, 104]]),
 array([159,  94,   0, 104, 116]))

In [168]:
index_to_word = np.load("data/index_to_word.npy", allow_pickle=True).item()
index_to_word

{0: 'ចូល',
 1: 'ស្ថាបត្យកម្ម',
 2: 'មួយ',
 3: 'ពី',
 4: 'ភ្នំ',
 5: 'ខាងលិច',
 6: 'ខ្មែរ',
 7: 'ចុង',
 8: 'ពួក',
 9: 'ជាមួយ',
 10: 'ច្រក',
 11: 'អ្នក',
 12: 'ប្រហែល',
 13: 'ទេវតា',
 14: 'ធំ',
 15: 'ក្នុង',
 16: 'គ្នា',
 17: 'ម៉ែត្រ',
 18: 'នឹង',
 19: 'លើ',
 20: 'ហើយ',
 21: 'ខ្ពស់',
 22: 'ចំពោះ',
 23: 'ព័ទ្ធ',
 24: 'ដូចជា',
 25: 'ទាំងអស់',
 26: 'ធ្វើ',
 27: 'ដើម',
 28: 'ឆ្នាំ',
 29: 'នៃ',
 30: 'ប្រមាណ',
 31: 'ក្បាច់',
 32: 'ផ្សេង',
 33: 'របស់',
 34: 'មិន',
 35: 'ឈ្មោះ',
 36: 'ចេញ',
 37: 'ស្រុក',
 38: 'បុរាណ',
 39: 'ដំបូង',
 40: 'អាច',
 41: 'អង្គរ',
 42: 'តំណាង',
 43: 'ខេត្ត',
 44: 'ប្រវែង',
 45: 'កំពែង',
 46: 'នោះ',
 47: 'ប្រទេស',
 48: 'តែ',
 49: 'សាសនា',
 50: 'នូវ',
 51: 'ប្រាសាទ',
 52: 'ដោយ',
 53: 'បី',
 54: 'ទៅ',
 55: 'ខាងក្រៅ',
 56: 'ថ្ម',
 57: 'ខាងជើង',
 58: 'នៅក្នុង',
 59: 'មក',
 60: 'សំណង់',
 61: 'សតវត្សរ៍',
 62: 'ទី',
 63: 'បុរៈ',
 64: 'ស្ថិត',
 65: 'ថ្ងៃ',
 66: 'ទឹក',
 67: 'ប៉ម',
 68: 'ពាក្យ',
 69: 'ដើម្បី',
 70: 'ដ៏',
 71: 'ឃើញ',
 72: 'គឺជា',
 73: 'នៅ',
 74: 'ដី',
 75: 'ថា',
 

In [169]:
X[0], y[0], [index_to_word[i] for i in X[0]], index_to_word[y[0]]

(array([ 51, 125, 161,  51,  41]),
 159,
 ['ប្រាសាទ', 'អង្គរវត្ត', 'ឬ', 'ប្រាសាទ', 'អង្គរ'],
 'តូច')

In [170]:
model.fit(X, y, epochs=100)

Epoch 1/100


20/20 [==============================] - 1s 4ms/step - loss: 4.0117 - accuracy: 0.3523
Epoch 2/100
20/20 [==============================] - 0s 4ms/step - loss: 3.4356 - accuracy: 0.3855
Epoch 3/100
20/20 [==============================] - 0s 5ms/step - loss: 3.3386 - accuracy: 0.3855
Epoch 4/100
20/20 [==============================] - 0s 4ms/step - loss: 3.2891 - accuracy: 0.3855
Epoch 5/100
20/20 [==============================] - 0s 4ms/step - loss: 3.2344 - accuracy: 0.3855
Epoch 6/100
20/20 [==============================] - 0s 4ms/step - loss: 3.2008 - accuracy: 0.3855
Epoch 7/100
20/20 [==============================] - 0s 4ms/step - loss: 3.1593 - accuracy: 0.3855
Epoch 8/100
20/20 [==============================] - 0s 4ms/step - loss: 3.1077 - accuracy: 0.3855
Epoch 9/100
20/20 [==============================] - 0s 4ms/step - loss: 3.0606 - accuracy: 0.3855
Epoch 10/100
20/20 [==============================] - 0s 4ms/step - loss: 3.0145 - accuracy: 0.3855
Epoch 11/100
20/20 [=

In [171]:
def predict_next_word(model, sentence):
    _tokens = word_tokenize(sentence)
    if len(_tokens) != N:
        raise ValueError(f"Expected {N} words, got {len(_tokens)}")
    x = np.array([[vocab.index(w) if w in vocab else 0 for w in _tokens]])
    y = model.predict(x)
    return index_to_word[np.argmax(y)]

In [172]:
word = "អង្គរវត្តឬប្រាសាទអង្គរតូច"
predict_next_word(model, word)

1/1 [==============================] - 0s 113ms/step


'មាន'

In [173]:
# Save model
model.save("models/III.keras")